//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientenDaten
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patienten
    {
        public int Id { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Geschlecht { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public string Krankenkasse { get; set; }
        public int Versicherungsnummer { get; set; }
        public string PLZ_Ort { get; set; }
        public string Straße_HausNr { get; set; }
        public string Telefon { get; set; }
        public string Besonderheiten { get; set; }
    }
}
