//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientenDaten
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termine
    {
        public int Id { get; set; }
        public int PatientenId { get; set; }
        public System.DateTime Datum { get; set; }
        public string Uhrzeit { get; set; }
        public string Beschreibung { get; set; }
    }
}
